Добавила чат
SPBSTU-OrangeTeam/QuipEditor pull request #1
Opened 2020-10-18 19:08 UTC by mandarin1029

2020-11-17 20:52 UTC, iOctav reviewed
We need to change some things

2020-11-17 20:52 UTC, iOctav commented on SublimeQuip.py
> +global comments
I believe that it's temporary solution

2020-11-17 20:52 UTC, iOctav commented on Default.sublime-keymap
> +	{ "keys": ["alt+a"], "command": "send_chat_message"},
Can we make it by click on some field in chat?

2020-11-17 20:52 UTC, iOctav commented on SublimeQuip.py
> +		current_window.show_input_panel('Сообщение для чата:', '', self._send_message, None, None)
In my view, customer wants English interface

2020-11-17 20:52 UTC, iOctav commented on SublimeQuip.py
> +	def _send_message(self, message):
double underscore at the start

2020-11-17 20:52 UTC, iOctav commented on SublimeQuip.py
> +		self.chat = sublime.active_window().open_file(comments)
Is it split view or new tab?

2020-11-18 10:10 UTC, mandarin1029 commented on SublimeQuip.py
> +global comments
Наверное
Я просто не понимаю, где вы собираетесь хранить файлы
Или локальных файлов вообще не будет?

2020-11-18 10:11 UTC, mandarin1029 commented on Default.sublime-keymap
> +	{ "keys": ["alt+a"], "command": "send_chat_message"},
Не совсем понимаю, какие именно поля ты имеешь в виду
Чат сейчас - это просто новое текстовое окно
Думаю, что нет

2020-11-18 10:12 UTC, iOctav commented on SublimeQuip.py
> +global comments
It's still a question. We may discuss it on the next meeting

2020-11-18 10:16 UTC, iOctav commented on Default.sublime-keymap
> +	{ "keys": ["alt+a"], "command": "send_chat_message"},
As I remember @SeveNChaK mentioned that we can insert mini html into page that is called phantom in Sublime

2020-11-18 10:17 UTC, mandarin1029 commented on SublimeQuip.py
> +		self.chat = sublime.active_window().open_file(comments)
Чат - это отдельное View (файл), который открывается в разделенном окне
Раздельное окно - это set_layout от sublime
Его можно и интерфейсом менять: View (сверху) -> Layout -> Columns: 2

2020-11-18 10:18 UTC, mandarin1029 commented on SublimeQuip.py
> +		current_window.show_input_panel('Сообщение для чата:', '', self._send_message, None, None)
Изменила надпись 
d893426

2020-11-18 10:18 UTC, mandarin1029 commented on SublimeQuip.py
> +	def _send_message(self, message):
Сделала
659ce70

2020-11-18 10:35 UTC, mandarin1029 commented on Default.sublime-keymap
> +	{ "keys": ["alt+a"], "command": "send_chat_message"},
Кто-то с ними разбирался уже? Или мне нужно посмотреть, можно ли чат вставить в виде phantom (html)?

2020-11-18 14:21 UTC, iOctav commented on Default.sublime-keymap
> +	{ "keys": ["alt+a"], "command": "send_chat_message"},
Discuss it with @SeveNChaK please

2020-12-03 16:37 UTC, iOctav commented
Hi, @mandarin1029 
I merged new methods into quip_provider for working with chat. Can you please use them instead of yours? 
Let's make chat as phantom (readonly) and we need to update it after sending message.
Also keep up to date tasks in the Trello

2020-12-06 21:09 UTC, iOctav requested changes

2020-12-06 21:09 UTC, iOctav commented on SublimeQuip.py
> +		self.chat.set_name(self.chat_name)
Scroll up window after showing chat

2020-12-06 21:09 UTC, iOctav commented on SublimeQuip.py
> +	def run(self):
We are going to open chat by link from main menu (with documents and contacts), which was created @SeveNChaK. Let's move open random chat to #test section at the down of this file

2020-12-06 21:09 UTC, iOctav commented on SublimeQuip.py
> +		current_window = sublime.active_window()
Verify that chat is opened before show input panel

2020-12-06 21:09 UTC, iOctav commented on src/quip_entity/message.py
> +    def to_json(self):
For what? What difference between to call property by string arg instead of to call property directly?

2020-12-06 21:09 UTC, iOctav commented on src/providers/quip_provider.py
> +        threads = self.quip_client.get_recent_threads()
We aren't going to use this method. It's useless

2020-12-06 21:09 UTC, iOctav commented on src/providers/quip_provider.py
> +        return self.quip_client.get_authenticated_user()
It is unnecessary method. We're getting user from get_contacts

2020-12-07 15:32 UTC, SeveNChaK commented on Default.sublime-keymap
> +	{ "keys": ["alt+a"], "command": "send_chat_message"},
Можно фантом будет сделать)

2020-12-07 15:38 UTC, SeveNChaK commented on SublimeQuip.py
> +		current_window = sublime.active_window()
Так а в следующей строке разве не такая проверка идет?

2020-12-07 17:28 UTC, merged