Чат фиксы
SPBSTU-OrangeTeam/QuipEditor pull request #8
Opened 2020-12-09 10:17 UTC by mandarin1029

https://trello.com/c/GPO5tj3N/38-Изменения-для-чата

2020-12-10 12:49 UTC, iOctav requested changes

2020-12-10 12:49 UTC, iOctav commented on src/quip_entity/message.py
> +        return "%s | %s [%s] %s: %s\n" % (self.author_id, self.author_name,
Let's remove new line '\n' here and will use it in join methods (e.g. '\n'.join(messages))

2020-12-10 12:49 UTC, iOctav commented on SublimeQuip.py
> +		result = ''.join(messages)
Join witnin new line '\n'

2020-12-11 08:28 UTC, mandarin1029 commented on SublimeQuip.py
> +		result = ''.join(messages)
2d34866

2020-12-11 08:38 UTC, iOctav approved these changes

2020-12-11 08:39 UTC, merged